"""This file is first migration file of translator app."""

# Generated by Django 4.2 on 2023-04-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This class is migration class for translate model.
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('from_language', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('to_language', models.CharField(max_length=500)),
                ('translation', models.TextField()),
            ],
        ),
    ]
