"""This file is second migration file of translator app."""

# Generated by Django 4.2 on 2023-04-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This class is migration class for translate model.
    """

    dependencies = [
        ('translator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
