"""This file is third migration file of translator app."""

# Generated by Django 4.2 on 2023-04-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This class is migration class for translate model.
    """

    dependencies = [
        ('translator_app', '0002_alter_translate_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='from_language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'),
                                            ('ES', 'Spanish'), ('ZH', 'Chinese')],
                                   max_length=500),
        ),
        migrations.AlterField(
            model_name='translate',
            name='to_language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'),
                                            ('ES', 'Spanish'), ('ZH', 'Chinese')],
                                   max_length=500),
        ),
        migrations.AlterField(
            model_name='translate',
            name='translation',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
